---
# See: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863199
- name: Ensure 'man' directory exists.
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'

- name: Install Required Ubuntu Packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk
    - apt-transport-https

- name: Import the signing key for the Neo Technology Debian repository for Neo4j
  apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key
    state: present

- name: Add the Neo Technology Debian repository for Neo4j
  apt_repository:
    repo: "deb https://debian.neo4j.org/repo stable/"
    state: present
    update_cache: true

- name: Install cypher-shell 1.1.12
  package:
    name: cypher-shell=1.1.12
    state: present
